#include "interpolation.h"
#include "motion_estimation.h" // for BlockSizePixels()
#include "logger.h"

#include <string>
#include "frame_interpolation_cs.h" // generated by fxc at build time
#include "upscale_cs.h"              // generated by fxc at build time

namespace FrameBoost::Interpolation {

namespace {
void SafeRelease(IUnknown* obj) {
    if (obj) obj->Release();
}

// D3D11 does not support creating an Unordered Access View directly on most
// _SRGB formats (Watch Dogs' back buffer is R8G8B8A8_UNORM_SRGB) - a compute
// shader UAV write always writes raw/linear bits, never sRGB-encodes. The
// standard fix: create the texture resource as the TYPELESS base format,
// then create an _SRGB view for reading (matches the source frames, correct
// sRGB->linear decode) and a plain _UNORM view for the UAV the shader writes
// through. Without this split, CreateUnorderedAccessView silently fails and
// the shader writes go nowhere - the generated texture stays whatever the
// driver zero-initialized it to (black), which is exactly the bug the first
// live Milestone 4 test hit.
void ResolveTypelessAndViewFormats(DXGI_FORMAT requested, DXGI_FORMAT& typelessOut,
                                    DXGI_FORMAT& srvFormatOut, DXGI_FORMAT& uavFormatOut) {
    switch (requested) {
        case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
            typelessOut = DXGI_FORMAT_R8G8B8A8_TYPELESS;
            srvFormatOut = DXGI_FORMAT_R8G8B8A8_UNORM_SRGB;
            uavFormatOut = DXGI_FORMAT_R8G8B8A8_UNORM;
            return;
        case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:
            typelessOut = DXGI_FORMAT_B8G8R8A8_TYPELESS;
            srvFormatOut = DXGI_FORMAT_B8G8R8A8_UNORM_SRGB;
            uavFormatOut = DXGI_FORMAT_B8G8R8A8_UNORM;
            return;
        default:
            // Not an sRGB format - no split needed, same format everywhere.
            typelessOut = requested;
            srvFormatOut = requested;
            uavFormatOut = requested;
            return;
    }
}
} // namespace

bool Interpolator::EnsureResources(ID3D11Device* device, UINT width, UINT height, DXGI_FORMAT format) {
    if (m_initialized && width == m_width && height == m_height && format == m_format)
        return true;

    SafeRelease(m_generatedTex); m_generatedTex = nullptr;
    SafeRelease(m_generatedUAV); m_generatedUAV = nullptr;
    SafeRelease(m_scaledTex); m_scaledTex = nullptr;
    SafeRelease(m_scaledUAV); m_scaledUAV = nullptr;
    SafeRelease(m_scaledSRV); m_scaledSRV = nullptr;
    m_scaledWidth = m_scaledHeight = 0;
    SafeRelease(m_paramsCB); m_paramsCB = nullptr;

    m_width = width;
    m_height = height;
    m_format = format;

    DXGI_FORMAT typelessFormat, srvFormat, uavFormat;
    ResolveTypelessAndViewFormats(format, typelessFormat, srvFormat, uavFormat);

    D3D11_TEXTURE2D_DESC texDesc{};
    texDesc.Width = width;
    texDesc.Height = height;
    texDesc.MipLevels = 1;
    texDesc.ArraySize = 1;
    texDesc.Format = typelessFormat;
    texDesc.SampleDesc.Count = 1;
    texDesc.Usage = D3D11_USAGE_DEFAULT;
    // Needs SHADER_RESOURCE too so it can be dumped for debug validation and
    // (Milestone 5) copied toward the real swapchain back buffer.
    texDesc.BindFlags = D3D11_BIND_UNORDERED_ACCESS | D3D11_BIND_SHADER_RESOURCE;

    if (FAILED(device->CreateTexture2D(&texDesc, nullptr, &m_generatedTex))) {
        Logger::Log("[FrameBoost] Interpolation: failed to create generated-frame texture.");
        return false;
    }

    D3D11_UNORDERED_ACCESS_VIEW_DESC uavDesc{};
    uavDesc.Format = uavFormat;
    uavDesc.ViewDimension = D3D11_UAV_DIMENSION_TEXTURE2D;
    uavDesc.Texture2D.MipSlice = 0;

    if (FAILED(device->CreateUnorderedAccessView(m_generatedTex, &uavDesc, &m_generatedUAV))) {
        Logger::Log("[FrameBoost] Interpolation: failed to create generated-frame UAV - "
            "the shader would silently write nowhere without this check.");
        return false;
    }

    if (!m_computeShader) {
        if (FAILED(device->CreateComputeShader(g_FrameInterpolationCS, sizeof(g_FrameInterpolationCS), nullptr, &m_computeShader))) {
            Logger::Log("[FrameBoost] Interpolation: failed to create compute shader.");
            return false;
        }
    }

    if (!m_upscaleShader) {
        if (FAILED(device->CreateComputeShader(g_UpscaleCS, sizeof(g_UpscaleCS), nullptr, &m_upscaleShader))) {
            Logger::Log("[FrameBoost] Interpolation: failed to create the upscale compute shader - "
                "half-density generation would have nothing to resample with.");
            return false;
        }
    }

    if (!m_linearClampSampler) {
        D3D11_SAMPLER_DESC sampDesc{};
        sampDesc.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
        sampDesc.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampDesc.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampDesc.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampDesc.ComparisonFunc = D3D11_COMPARISON_NEVER;
        device->CreateSamplerState(&sampDesc, &m_linearClampSampler);
    }

    // Field order and padding MUST match the HLSL cbuffer register for
    // register, which this did not.
    //
    // HLSL packs constant buffers into 16-byte registers and no field may
    // straddle one. The declared order there is PhaseT, ExtrapolateAhead,
    // MousePrediction.xy | QualityRelief, MotionCutoff, StatusFlags. This
    // struct had statusFlags third, so every field from byte 20 on was read as
    // the wrong one:
    //
    //   byte 20  C++ statusFlags      -> shader ExtrapolateAhead
    //   byte 24  C++ extrapolateAhead -> shader MousePrediction.x
    //   byte 28  C++ pad (zero)       -> shader MousePrediction.y
    //   byte 32  C++ mousePredictX    -> shader QualityRelief
    //   byte 40  C++ qualityRelief    -> shader StatusFlags
    //
    // MousePrediction was therefore ALWAYS (0, 0), so the shader's
    // "if (any(MousePrediction != 0.0))" never fired once and the mouse was
    // never offered as a motion candidate - while the engine went on measuring
    // and logging a calibration it could not use (3700 samples, correlation
    // 0.74). And StatusFlags read the bit pattern of 1.0f, 0x3F800000, whose
    // bit 2 is clear, which is why the green badge was never drawn.
    //
    // It survived this long because the two fields that would have been
    // visibly wrong both landed on harmless values: ExtrapolateAhead read
    // small integer flags as a float, and those are denormals that D3D11
    // flushes to zero, so the extrapolation branch stayed off; QualityRelief
    // read a number that max(x, 1.0) turns into 1.0, which is what it is
    // pinned at anyway.
    struct ParamsCB {
        UINT width, height, blockSize, debugTint;                      // b0
        float phaseT, extrapolateAhead, qualityRelief, motionCutoff;   // b1
        UINT statusFlags, interpScale, warpFilter, _pad2;               // b2
    };
    ParamsCB params{ m_width, m_height, MotionEstimation::Estimator::BlockSizePixels(), m_debugTint,
                     m_phaseT, m_extrapolateAhead, m_qualityRelief, m_motionCutoff,
                     m_statusFlags, m_interpScale, m_warpFilter, 0u };
    m_debugTintInBuffer = m_debugTint;
    m_phaseTInBuffer = m_phaseT;
    m_statusFlagsInBuffer = m_statusFlags;
    m_interpScaleInBuffer = m_interpScale;
    m_warpFilterInBuffer = m_warpFilter;
    D3D11_BUFFER_DESC cbDesc{};
    cbDesc.ByteWidth = sizeof(ParamsCB);
    cbDesc.Usage = D3D11_USAGE_DEFAULT;
    cbDesc.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    D3D11_SUBRESOURCE_DATA cbInit{ &params, 0, 0 };
    device->CreateBuffer(&cbDesc, &cbInit, &m_paramsCB);

    if (!m_queries[0].disjoint) {
        for (auto& q : m_queries) {
            D3D11_QUERY_DESC disjointDesc{ D3D11_QUERY_TIMESTAMP_DISJOINT, 0 };
            D3D11_QUERY_DESC timestampDesc{ D3D11_QUERY_TIMESTAMP, 0 };
            device->CreateQuery(&disjointDesc, &q.disjoint);
            device->CreateQuery(&timestampDesc, &q.start);
            device->CreateQuery(&timestampDesc, &q.end);
        }
    }

    m_initialized = true;
    Logger::Log("[FrameBoost] Interpolation resources created: " + std::to_string(width) + "x" + std::to_string(height));
    return true;
}

void Interpolator::ResolvePendingGpuTiming(ID3D11DeviceContext* context) {
    int readIndex = (m_queryWriteIndex + 1) % kQueryRingSize;
    QuerySet& q = m_queries[readIndex];
    if (!q.pending) return;

    D3D11_QUERY_DATA_TIMESTAMP_DISJOINT disjointData{};
    if (context->GetData(q.disjoint, &disjointData, sizeof(disjointData), 0) != S_OK) return;

    UINT64 start = 0, end = 0;
    if (context->GetData(q.start, &start, sizeof(start), 0) != S_OK) return;
    if (context->GetData(q.end, &end, sizeof(end), 0) != S_OK) return;

    q.pending = false;
    if (disjointData.Disjoint || disjointData.Frequency == 0) return;

    m_lastGpuTimeMs = static_cast<double>(end - start) / disjointData.Frequency * 1000.0;
}

bool Interpolator::GenerateFrame(ID3D11Device* device, ID3D11DeviceContext* context,
                                  ID3D11ShaderResourceView* prevSRV, ID3D11ShaderResourceView* currSRV,
                                  ID3D11ShaderResourceView* motionSRV, UINT width, UINT height, DXGI_FORMAT format,
                                  ID3D11UnorderedAccessView* targetUAV) {
    if (!prevSRV || !currSRV || !motionSRV) return false;
    if (!EnsureResources(device, width, height, format)) return false;

    // The debug tint and the phase both live in the same constant buffer as
    // the frame dimensions, so changing either needs a buffer update rather
    // than a full resource rebuild. The phase changes for every generated
    // frame at factors above 2x, so this is on the hot path - but it is a
    // 32-byte upload, which is why the whole multi-frame scheme costs
    // essentially nothing beyond the extra dispatches themselves.
    if ((m_debugTint != m_debugTintInBuffer || m_phaseT != m_phaseTInBuffer
            || m_extrapolateAhead != m_extrapolateAheadInBuffer
            || m_qualityRelief != m_qualityReliefInBuffer
            || m_motionCutoff != m_motionCutoffInBuffer
            || m_statusFlags != m_statusFlagsInBuffer
            || m_interpScale != m_interpScaleInBuffer
            || m_warpFilter != m_warpFilterInBuffer) && m_paramsCB) {
        // Same layout as at creation - see the comment there.
    struct ParamsCB {
        UINT width, height, blockSize, debugTint;                      // b0
        float phaseT, extrapolateAhead, qualityRelief, motionCutoff;   // b1
        UINT statusFlags, interpScale, warpFilter, _pad2;               // b2
    };
        ParamsCB params{ m_width, m_height, MotionEstimation::Estimator::BlockSizePixels(), m_debugTint,
                     m_phaseT, m_extrapolateAhead, m_qualityRelief, m_motionCutoff,
                     m_statusFlags, m_interpScale, m_warpFilter, 0u };
        context->UpdateSubresource(m_paramsCB, 0, nullptr, &params, 0, 0);
        m_debugTintInBuffer = m_debugTint;
        m_phaseTInBuffer = m_phaseT;
        m_extrapolateAheadInBuffer = m_extrapolateAhead;
        m_qualityReliefInBuffer = m_qualityRelief;
        m_motionCutoffInBuffer = m_motionCutoff;
        m_statusFlagsInBuffer = m_statusFlags;
        m_interpScaleInBuffer = m_interpScale;
        m_warpFilterInBuffer = m_warpFilter;
    }

    QuerySet& q = m_queries[m_queryWriteIndex];
    context->Begin(q.disjoint);
    context->End(q.start);

    // One invocation per output texel of whatever the target is. At scale 2
    // that target is the half-resolution intermediate, so a quarter of the
    // invocations - and then a second pass resamples it up.
    const UINT scale = m_interpScale < 1u ? 1u : m_interpScale;
    const UINT scaledW = (width + scale - 1) / scale;
    const UINT scaledH = (height + scale - 1) / scale;

    ID3D11UnorderedAccessView* finalUAV = targetUAV ? targetUAV : m_generatedUAV;
    const bool twoPass = (scale > 1) && EnsureScaledTarget(device, scaledW, scaledH, format);

    ID3D11ShaderResourceView* srvs[3] = { prevSRV, currSRV, motionSRV };
    context->CSSetShaderResources(0, 3, srvs);
    ID3D11UnorderedAccessView* outputUAV = twoPass ? m_scaledUAV : finalUAV;
    context->CSSetUnorderedAccessViews(0, 1, &outputUAV, nullptr);
    context->CSSetSamplers(0, 1, &m_linearClampSampler);
    context->CSSetConstantBuffers(0, 1, &m_paramsCB);
    context->CSSetShader(m_computeShader, nullptr, 0);

    context->Dispatch((scaledW + 7) / 8, (scaledH + 7) / 8, 1);

    ID3D11ShaderResourceView* nullSrvs[3] = { nullptr, nullptr, nullptr };
    context->CSSetShaderResources(0, 3, nullSrvs);
    ID3D11UnorderedAccessView* nullUav = nullptr;
    context->CSSetUnorderedAccessViews(0, 1, &nullUav, nullptr);

    if (twoPass) {
        // PASS TWO: one bilinear tap per output pixel.
        //
        // The texture unit does the filtering in hardware, so this costs a read
        // and a write per pixel and nothing else - far less than the quarter of
        // the interpolation work it buys back in sharpness.
        //
        // Both views must be unbound before rebinding: m_scaledUAV was the
        // output a moment ago and is the input now, and D3D11 will silently
        // drop one of the two bindings if both are live.
        context->CSSetShaderResources(0, 1, &m_scaledSRV);
        context->CSSetUnorderedAccessViews(0, 1, &finalUAV, nullptr);
        context->CSSetSamplers(0, 1, &m_linearClampSampler);
        context->CSSetConstantBuffers(0, 1, &m_paramsCB);
        context->CSSetShader(m_upscaleShader, nullptr, 0);

        context->Dispatch((width + 7) / 8, (height + 7) / 8, 1);

        ID3D11ShaderResourceView* nullSrv = nullptr;
        context->CSSetShaderResources(0, 1, &nullSrv);
        context->CSSetUnorderedAccessViews(0, 1, &nullUav, nullptr);
    }

    context->End(q.end);
    context->End(q.disjoint);
    q.pending = true;
    m_queryWriteIndex = (m_queryWriteIndex + 1) % kQueryRingSize;

    ResolvePendingGpuTiming(context);
    return true;
}

// The half-resolution intermediate. Created on demand, rebuilt when the frame
// size or the scale changes, and never created at all while InterpScale is 1.
//
// Same typeless/SRGB split as the generated texture: a UAV cannot be created on
// most _SRGB formats, so the resource is typeless, the UAV is UNORM and the SRV
// carries the real format - here that also matters for the filtering, because
// the bilinear blend has to happen after the sRGB decode, not on the encoded
// bits.
bool Interpolator::EnsureScaledTarget(ID3D11Device* device, UINT width, UINT height,
                                      DXGI_FORMAT format) {
    if (m_scaledTex && m_scaledWidth == width && m_scaledHeight == height) return true;

    SafeRelease(m_scaledTex); m_scaledTex = nullptr;
    SafeRelease(m_scaledUAV); m_scaledUAV = nullptr;
    SafeRelease(m_scaledSRV); m_scaledSRV = nullptr;
    m_scaledWidth = m_scaledHeight = 0;

    DXGI_FORMAT typelessFormat, srvFormat, uavFormat;
    ResolveTypelessAndViewFormats(format, typelessFormat, srvFormat, uavFormat);

    D3D11_TEXTURE2D_DESC texDesc{};
    texDesc.Width = width;
    texDesc.Height = height;
    texDesc.MipLevels = 1;
    texDesc.ArraySize = 1;
    texDesc.Format = typelessFormat;
    texDesc.SampleDesc.Count = 1;
    texDesc.Usage = D3D11_USAGE_DEFAULT;
    texDesc.BindFlags = D3D11_BIND_UNORDERED_ACCESS | D3D11_BIND_SHADER_RESOURCE;
    if (FAILED(device->CreateTexture2D(&texDesc, nullptr, &m_scaledTex))) {
        Logger::Log("[FrameBoost] Interpolation: failed to create the half-resolution target - "
            "falling back to writing the frame at full density.");
        return false;
    }

    D3D11_UNORDERED_ACCESS_VIEW_DESC uavDesc{};
    uavDesc.Format = uavFormat;
    uavDesc.ViewDimension = D3D11_UAV_DIMENSION_TEXTURE2D;
    uavDesc.Texture2D.MipSlice = 0;
    if (FAILED(device->CreateUnorderedAccessView(m_scaledTex, &uavDesc, &m_scaledUAV))) {
        Logger::Log("[FrameBoost] Interpolation: failed to create the half-resolution UAV.");
        SafeRelease(m_scaledTex); m_scaledTex = nullptr;
        return false;
    }

    D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc{};
    srvDesc.Format = srvFormat;
    srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
    srvDesc.Texture2D.MipLevels = 1;
    if (FAILED(device->CreateShaderResourceView(m_scaledTex, &srvDesc, &m_scaledSRV))) {
        Logger::Log("[FrameBoost] Interpolation: failed to create the half-resolution SRV.");
        SafeRelease(m_scaledTex); m_scaledTex = nullptr;
        SafeRelease(m_scaledUAV); m_scaledUAV = nullptr;
        return false;
    }

    m_scaledWidth = width;
    m_scaledHeight = height;
    Logger::Log("[FrameBoost] Interpolation: half-resolution target "
        + std::to_string(width) + "x" + std::to_string(height)
        + " with a bilinear upscale pass.");
    return true;
}

Interpolator::~Interpolator() {
    SafeRelease(m_generatedTex);
    SafeRelease(m_generatedUAV);
    SafeRelease(m_scaledTex);
    SafeRelease(m_scaledUAV);
    SafeRelease(m_scaledSRV);
    SafeRelease(m_upscaleShader);
    SafeRelease(m_computeShader);
    SafeRelease(m_linearClampSampler);
    SafeRelease(m_paramsCB);
    for (auto& q : m_queries) {
        SafeRelease(q.disjoint);
        SafeRelease(q.start);
        SafeRelease(q.end);
    }
}

} // namespace FrameBoost::Interpolation
