#include "interpolation.h"
#include "motion_estimation.h" // for BlockSizePixels()
#include "logger.h"

#include <string>
#include "frame_interpolation_cs.h" // generated by fxc at build time

namespace FrameBoost::Interpolation {

namespace {
void SafeRelease(IUnknown* obj) {
    if (obj) obj->Release();
}

// D3D11 does not support creating an Unordered Access View directly on most
// _SRGB formats (Watch Dogs' back buffer is R8G8B8A8_UNORM_SRGB) - a compute
// shader UAV write always writes raw/linear bits, never sRGB-encodes. The
// standard fix: create the texture resource as the TYPELESS base format,
// then create an _SRGB view for reading (matches the source frames, correct
// sRGB->linear decode) and a plain _UNORM view for the UAV the shader writes
// through. Without this split, CreateUnorderedAccessView silently fails and
// the shader writes go nowhere - the generated texture stays whatever the
// driver zero-initialized it to (black), which is exactly the bug the first
// live Milestone 4 test hit.
void ResolveTypelessAndViewFormats(DXGI_FORMAT requested, DXGI_FORMAT& typelessOut,
                                    DXGI_FORMAT& srvFormatOut, DXGI_FORMAT& uavFormatOut) {
    switch (requested) {
        case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
            typelessOut = DXGI_FORMAT_R8G8B8A8_TYPELESS;
            srvFormatOut = DXGI_FORMAT_R8G8B8A8_UNORM_SRGB;
            uavFormatOut = DXGI_FORMAT_R8G8B8A8_UNORM;
            return;
        case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:
            typelessOut = DXGI_FORMAT_B8G8R8A8_TYPELESS;
            srvFormatOut = DXGI_FORMAT_B8G8R8A8_UNORM_SRGB;
            uavFormatOut = DXGI_FORMAT_B8G8R8A8_UNORM;
            return;
        default:
            // Not an sRGB format - no split needed, same format everywhere.
            typelessOut = requested;
            srvFormatOut = requested;
            uavFormatOut = requested;
            return;
    }
}
} // namespace

bool Interpolator::EnsureResources(ID3D11Device* device, UINT width, UINT height, DXGI_FORMAT format) {
    if (m_initialized && width == m_width && height == m_height && format == m_format)
        return true;

    SafeRelease(m_generatedTex); m_generatedTex = nullptr;
    SafeRelease(m_generatedUAV); m_generatedUAV = nullptr;
    SafeRelease(m_paramsCB); m_paramsCB = nullptr;

    m_width = width;
    m_height = height;
    m_format = format;

    DXGI_FORMAT typelessFormat, srvFormat, uavFormat;
    ResolveTypelessAndViewFormats(format, typelessFormat, srvFormat, uavFormat);

    D3D11_TEXTURE2D_DESC texDesc{};
    texDesc.Width = width;
    texDesc.Height = height;
    texDesc.MipLevels = 1;
    texDesc.ArraySize = 1;
    texDesc.Format = typelessFormat;
    texDesc.SampleDesc.Count = 1;
    texDesc.Usage = D3D11_USAGE_DEFAULT;
    // Needs SHADER_RESOURCE too so it can be dumped for debug validation and
    // (Milestone 5) copied toward the real swapchain back buffer.
    texDesc.BindFlags = D3D11_BIND_UNORDERED_ACCESS | D3D11_BIND_SHADER_RESOURCE;

    if (FAILED(device->CreateTexture2D(&texDesc, nullptr, &m_generatedTex))) {
        Logger::Log("[FrameBoost] Interpolation: failed to create generated-frame texture.");
        return false;
    }

    D3D11_UNORDERED_ACCESS_VIEW_DESC uavDesc{};
    uavDesc.Format = uavFormat;
    uavDesc.ViewDimension = D3D11_UAV_DIMENSION_TEXTURE2D;
    uavDesc.Texture2D.MipSlice = 0;

    if (FAILED(device->CreateUnorderedAccessView(m_generatedTex, &uavDesc, &m_generatedUAV))) {
        Logger::Log("[FrameBoost] Interpolation: failed to create generated-frame UAV - "
            "the shader would silently write nowhere without this check.");
        return false;
    }

    if (!m_computeShader) {
        if (FAILED(device->CreateComputeShader(g_FrameInterpolationCS, sizeof(g_FrameInterpolationCS), nullptr, &m_computeShader))) {
            Logger::Log("[FrameBoost] Interpolation: failed to create compute shader.");
            return false;
        }
    }

    if (!m_linearClampSampler) {
        D3D11_SAMPLER_DESC sampDesc{};
        sampDesc.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
        sampDesc.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampDesc.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampDesc.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        sampDesc.ComparisonFunc = D3D11_COMPARISON_NEVER;
        device->CreateSamplerState(&sampDesc, &m_linearClampSampler);
    }

    struct ParamsCB { UINT width, height, blockSize, debugTint; };
    ParamsCB params{ m_width, m_height, MotionEstimation::Estimator::BlockSizePixels(), m_debugTint ? 1u : 0u };
    m_debugTintInBuffer = m_debugTint;
    D3D11_BUFFER_DESC cbDesc{};
    cbDesc.ByteWidth = sizeof(ParamsCB);
    cbDesc.Usage = D3D11_USAGE_DEFAULT;
    cbDesc.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    D3D11_SUBRESOURCE_DATA cbInit{ &params, 0, 0 };
    device->CreateBuffer(&cbDesc, &cbInit, &m_paramsCB);

    if (!m_queries[0].disjoint) {
        for (auto& q : m_queries) {
            D3D11_QUERY_DESC disjointDesc{ D3D11_QUERY_TIMESTAMP_DISJOINT, 0 };
            D3D11_QUERY_DESC timestampDesc{ D3D11_QUERY_TIMESTAMP, 0 };
            device->CreateQuery(&disjointDesc, &q.disjoint);
            device->CreateQuery(&timestampDesc, &q.start);
            device->CreateQuery(&timestampDesc, &q.end);
        }
    }

    m_initialized = true;
    Logger::Log("[FrameBoost] Interpolation resources created: " + std::to_string(width) + "x" + std::to_string(height));
    return true;
}

void Interpolator::ResolvePendingGpuTiming(ID3D11DeviceContext* context) {
    int readIndex = (m_queryWriteIndex + 1) % kQueryRingSize;
    QuerySet& q = m_queries[readIndex];
    if (!q.pending) return;

    D3D11_QUERY_DATA_TIMESTAMP_DISJOINT disjointData{};
    if (context->GetData(q.disjoint, &disjointData, sizeof(disjointData), 0) != S_OK) return;

    UINT64 start = 0, end = 0;
    if (context->GetData(q.start, &start, sizeof(start), 0) != S_OK) return;
    if (context->GetData(q.end, &end, sizeof(end), 0) != S_OK) return;

    q.pending = false;
    if (disjointData.Disjoint || disjointData.Frequency == 0) return;

    m_lastGpuTimeMs = static_cast<double>(end - start) / disjointData.Frequency * 1000.0;
}

bool Interpolator::GenerateFrame(ID3D11Device* device, ID3D11DeviceContext* context,
                                  ID3D11ShaderResourceView* prevSRV, ID3D11ShaderResourceView* currSRV,
                                  ID3D11ShaderResourceView* motionSRV, UINT width, UINT height, DXGI_FORMAT format) {
    if (!prevSRV || !currSRV || !motionSRV) return false;
    if (!EnsureResources(device, width, height, format)) return false;

    // The debug tint lives in the same constant buffer as the frame
    // dimensions, so toggling it needs a buffer update rather than a full
    // resource rebuild.
    if (m_debugTint != m_debugTintInBuffer && m_paramsCB) {
        struct ParamsCB { UINT width, height, blockSize, debugTint; };
        ParamsCB params{ m_width, m_height, MotionEstimation::Estimator::BlockSizePixels(), m_debugTint ? 1u : 0u };
        context->UpdateSubresource(m_paramsCB, 0, nullptr, &params, 0, 0);
        m_debugTintInBuffer = m_debugTint;
    }

    QuerySet& q = m_queries[m_queryWriteIndex];
    context->Begin(q.disjoint);
    context->End(q.start);

    ID3D11ShaderResourceView* srvs[3] = { prevSRV, currSRV, motionSRV };
    context->CSSetShaderResources(0, 3, srvs);
    context->CSSetUnorderedAccessViews(0, 1, &m_generatedUAV, nullptr);
    context->CSSetSamplers(0, 1, &m_linearClampSampler);
    context->CSSetConstantBuffers(0, 1, &m_paramsCB);
    context->CSSetShader(m_computeShader, nullptr, 0);

    UINT groupsX = (width + 7) / 8;
    UINT groupsY = (height + 7) / 8;
    context->Dispatch(groupsX, groupsY, 1);

    ID3D11ShaderResourceView* nullSrvs[3] = { nullptr, nullptr, nullptr };
    context->CSSetShaderResources(0, 3, nullSrvs);
    ID3D11UnorderedAccessView* nullUav = nullptr;
    context->CSSetUnorderedAccessViews(0, 1, &nullUav, nullptr);

    context->End(q.end);
    context->End(q.disjoint);
    q.pending = true;
    m_queryWriteIndex = (m_queryWriteIndex + 1) % kQueryRingSize;

    ResolvePendingGpuTiming(context);
    return true;
}

Interpolator::~Interpolator() {
    SafeRelease(m_generatedTex);
    SafeRelease(m_generatedUAV);
    SafeRelease(m_computeShader);
    SafeRelease(m_linearClampSampler);
    SafeRelease(m_paramsCB);
    for (auto& q : m_queries) {
        SafeRelease(q.disjoint);
        SafeRelease(q.start);
        SafeRelease(q.end);
    }
}

} // namespace FrameBoost::Interpolation
