#include "motion_estimation.h"
#include "logger.h"

#include <string>
#include "motion_estimation_cs.h" // generated by fxc at build time, see CMakeLists.txt
#include "motion_smooth_cs.h"

namespace FrameBoost::MotionEstimation {

namespace {
// MUST stay in sync with kBlockSize in motion_estimation.hlsl and with
// Estimator::BlockSizePixels() - the dispatch grid, the shader's block
// origin maths and the interpolation shader's block lookup all depend on
// these agreeing.
constexpr UINT kBlockSize = 16;

void SafeRelease(IUnknown* obj) {
    if (obj) obj->Release();
}
} // namespace

bool Estimator::EnsureResources(ID3D11Device* device, const D3D11_TEXTURE2D_DESC& frameDesc) {
    if (m_initialized && frameDesc.Width == m_width && frameDesc.Height == m_height)
        return true;

    // Resolution changed (or first run) - (re)create every GPU resource.
    SafeRelease(m_prevFrameTex); m_prevFrameTex = nullptr;
    SafeRelease(m_currFrameTex); m_currFrameTex = nullptr;
    SafeRelease(m_prevFrameSRV); m_prevFrameSRV = nullptr;
    SafeRelease(m_currFrameSRV); m_currFrameSRV = nullptr;
    SafeRelease(m_motionVectorRawTex); m_motionVectorRawTex = nullptr;
    SafeRelease(m_motionVectorRawUAV); m_motionVectorRawUAV = nullptr;
    SafeRelease(m_motionVectorRawSRV); m_motionVectorRawSRV = nullptr;
    SafeRelease(m_motionVectorSmoothTex); m_motionVectorSmoothTex = nullptr;
    SafeRelease(m_motionVectorSmoothUAV); m_motionVectorSmoothUAV = nullptr;
    SafeRelease(m_motionVectorSmoothSRV); m_motionVectorSmoothSRV = nullptr;
    SafeRelease(m_frameDimsCB); m_frameDimsCB = nullptr;
    SafeRelease(m_blockGridDimsCB); m_blockGridDimsCB = nullptr;
    m_havePrevFrame = false;

    m_width = frameDesc.Width;
    m_height = frameDesc.Height;
    m_blockCountX = (m_width + kBlockSize - 1) / kBlockSize;
    m_blockCountY = (m_height + kBlockSize - 1) / kBlockSize;

    D3D11_TEXTURE2D_DESC frameTexDesc = frameDesc;
    frameTexDesc.Usage = D3D11_USAGE_DEFAULT;
    frameTexDesc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
    frameTexDesc.CPUAccessFlags = 0;
    frameTexDesc.MiscFlags = 0;
    frameTexDesc.SampleDesc.Count = 1;
    frameTexDesc.SampleDesc.Quality = 0;
    frameTexDesc.MipLevels = 1;
    frameTexDesc.ArraySize = 1;

    if (FAILED(device->CreateTexture2D(&frameTexDesc, nullptr, &m_prevFrameTex)) ||
        FAILED(device->CreateTexture2D(&frameTexDesc, nullptr, &m_currFrameTex))) {
        Logger::Log("[FrameBoost] Motion estimation: failed to create frame textures.");
        return false;
    }

    device->CreateShaderResourceView(m_prevFrameTex, nullptr, &m_prevFrameSRV);
    device->CreateShaderResourceView(m_currFrameTex, nullptr, &m_currFrameSRV);

    D3D11_TEXTURE2D_DESC mvDesc{};
    mvDesc.Width = m_blockCountX;
    mvDesc.Height = m_blockCountY;
    mvDesc.MipLevels = 1;
    mvDesc.ArraySize = 1;
    mvDesc.Format = DXGI_FORMAT_R32G32_FLOAT;
    mvDesc.SampleDesc.Count = 1;
    mvDesc.Usage = D3D11_USAGE_DEFAULT;
    mvDesc.BindFlags = D3D11_BIND_UNORDERED_ACCESS | D3D11_BIND_SHADER_RESOURCE;

    if (FAILED(device->CreateTexture2D(&mvDesc, nullptr, &m_motionVectorRawTex)) ||
        FAILED(device->CreateTexture2D(&mvDesc, nullptr, &m_motionVectorSmoothTex))) {
        Logger::Log("[FrameBoost] Motion estimation: failed to create motion vector textures.");
        return false;
    }
    device->CreateUnorderedAccessView(m_motionVectorRawTex, nullptr, &m_motionVectorRawUAV);
    device->CreateShaderResourceView(m_motionVectorRawTex, nullptr, &m_motionVectorRawSRV);
    device->CreateUnorderedAccessView(m_motionVectorSmoothTex, nullptr, &m_motionVectorSmoothUAV);
    device->CreateShaderResourceView(m_motionVectorSmoothTex, nullptr, &m_motionVectorSmoothSRV);

    if (!m_computeShader) {
        if (FAILED(device->CreateComputeShader(g_MotionEstimationCS, sizeof(g_MotionEstimationCS), nullptr, &m_computeShader))) {
            Logger::Log("[FrameBoost] Motion estimation: failed to create block-matching compute shader.");
            return false;
        }
    }
    if (!m_smoothShader) {
        if (FAILED(device->CreateComputeShader(g_MotionSmoothCS, sizeof(g_MotionSmoothCS), nullptr, &m_smoothShader))) {
            Logger::Log("[FrameBoost] Motion estimation: failed to create smoothing compute shader.");
            return false;
        }
    }

    struct FrameDimsCB { UINT width, height, pad0, pad1; };
    FrameDimsCB frameDims{ m_width, m_height, 0, 0 };
    D3D11_BUFFER_DESC cbDesc{};
    cbDesc.ByteWidth = sizeof(FrameDimsCB);
    cbDesc.Usage = D3D11_USAGE_DEFAULT;
    cbDesc.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    D3D11_SUBRESOURCE_DATA cbInit{ &frameDims, 0, 0 };
    device->CreateBuffer(&cbDesc, &cbInit, &m_frameDimsCB);

    struct BlockGridDimsCB { UINT blockCountX, blockCountY, pad0, pad1; };
    BlockGridDimsCB gridDims{ m_blockCountX, m_blockCountY, 0, 0 };
    D3D11_SUBRESOURCE_DATA gridCbInit{ &gridDims, 0, 0 };
    device->CreateBuffer(&cbDesc, &gridCbInit, &m_blockGridDimsCB);

    if (!m_queries[0].disjoint) {
        for (auto& q : m_queries) {
            D3D11_QUERY_DESC disjointDesc{ D3D11_QUERY_TIMESTAMP_DISJOINT, 0 };
            D3D11_QUERY_DESC timestampDesc{ D3D11_QUERY_TIMESTAMP, 0 };
            device->CreateQuery(&disjointDesc, &q.disjoint);
            device->CreateQuery(&timestampDesc, &q.start);
            device->CreateQuery(&timestampDesc, &q.end);
        }
    }

    m_initialized = true;
    Logger::Log("[FrameBoost] Motion estimation resources created: "
        + std::to_string(m_width) + "x" + std::to_string(m_height)
        + " -> " + std::to_string(m_blockCountX) + "x" + std::to_string(m_blockCountY) + " blocks.");
    return true;
}

void Estimator::ResolvePendingGpuTiming(ID3D11DeviceContext* context) {
    // Read the OLDEST still-pending query set - by now (kQueryRingSize
    // frames later) the GPU has essentially always finished, so GetData
    // does not stall.
    int readIndex = (m_queryWriteIndex + 1) % kQueryRingSize;
    QuerySet& q = m_queries[readIndex];
    if (!q.pending) return;

    D3D11_QUERY_DATA_TIMESTAMP_DISJOINT disjointData{};
    if (context->GetData(q.disjoint, &disjointData, sizeof(disjointData), 0) != S_OK) return;

    UINT64 start = 0, end = 0;
    if (context->GetData(q.start, &start, sizeof(start), 0) != S_OK) return;
    if (context->GetData(q.end, &end, sizeof(end), 0) != S_OK) return;

    q.pending = false;
    if (disjointData.Disjoint || disjointData.Frequency == 0) return;

    // Covers BOTH GPU passes (block-matching + smoothing) since the
    // timestamps now bracket both dispatches - the number logged is the
    // real total motion-estimation cost, not just one half of it.
    m_lastGpuTimeMs = static_cast<double>(end - start) / disjointData.Frequency * 1000.0;
}

bool Estimator::ProcessFrame(ID3D11Device* device, ID3D11DeviceContext* context, ID3D11Texture2D* backBuffer) {
    D3D11_TEXTURE2D_DESC desc{};
    backBuffer->GetDesc(&desc);

    if (!EnsureResources(device, desc))
        return false;

    context->CopyResource(m_currFrameTex, backBuffer);

    bool computedThisFrame = false;

    if (m_havePrevFrame) {
        QuerySet& q = m_queries[m_queryWriteIndex];
        context->Begin(q.disjoint);
        context->End(q.start);

        // Pass 1: real block-matching motion estimation (noisy on detailed
        // scenes on its own - see Pass 2).
        ID3D11ShaderResourceView* srvs[2] = { m_prevFrameSRV, m_currFrameSRV };
        context->CSSetShaderResources(0, 2, srvs);
        context->CSSetUnorderedAccessViews(0, 1, &m_motionVectorRawUAV, nullptr);
        context->CSSetConstantBuffers(0, 1, &m_frameDimsCB);
        context->CSSetShader(m_computeShader, nullptr, 0);
        context->Dispatch(m_blockCountX, m_blockCountY, 1);

        ID3D11ShaderResourceView* nullSrvs[2] = { nullptr, nullptr };
        context->CSSetShaderResources(0, 2, nullSrvs);
        ID3D11UnorderedAccessView* nullUav = nullptr;
        context->CSSetUnorderedAccessViews(0, 1, &nullUav, nullptr);

        // Pass 2: 3x3 spatial smoothing over the raw field - the real fix
        // for the speckle noise seen on the first live test against Watch
        // Dogs. Dispatched in 8x8 thread groups over the (small) block grid.
        context->CSSetShaderResources(0, 1, &m_motionVectorRawSRV);
        context->CSSetUnorderedAccessViews(0, 1, &m_motionVectorSmoothUAV, nullptr);
        context->CSSetConstantBuffers(0, 1, &m_blockGridDimsCB);
        context->CSSetShader(m_smoothShader, nullptr, 0);
        UINT groupsX = (m_blockCountX + 7) / 8;
        UINT groupsY = (m_blockCountY + 7) / 8;
        context->Dispatch(groupsX, groupsY, 1);

        ID3D11ShaderResourceView* nullSrv1[1] = { nullptr };
        context->CSSetShaderResources(0, 1, nullSrv1);
        context->CSSetUnorderedAccessViews(0, 1, &nullUav, nullptr);

        context->End(q.end);
        context->End(q.disjoint);
        q.pending = true;
        m_queryWriteIndex = (m_queryWriteIndex + 1) % kQueryRingSize;

        ResolvePendingGpuTiming(context);
        computedThisFrame = true;
    }

    // Current becomes previous for the next frame - stays entirely GPU-side.
    context->CopyResource(m_prevFrameTex, m_currFrameTex);
    m_havePrevFrame = true;

    return computedThisFrame;
}

Estimator::~Estimator() {
    SafeRelease(m_prevFrameTex);
    SafeRelease(m_currFrameTex);
    SafeRelease(m_prevFrameSRV);
    SafeRelease(m_currFrameSRV);
    SafeRelease(m_motionVectorRawTex);
    SafeRelease(m_motionVectorRawUAV);
    SafeRelease(m_motionVectorRawSRV);
    SafeRelease(m_motionVectorSmoothTex);
    SafeRelease(m_motionVectorSmoothUAV);
    SafeRelease(m_motionVectorSmoothSRV);
    SafeRelease(m_computeShader);
    SafeRelease(m_smoothShader);
    SafeRelease(m_frameDimsCB);
    SafeRelease(m_blockGridDimsCB);
    for (auto& q : m_queries) {
        SafeRelease(q.disjoint);
        SafeRelease(q.start);
        SafeRelease(q.end);
    }
}

} // namespace FrameBoost::MotionEstimation
