#include "motion_estimation.h"
#include "logger.h"

#include <string>
#include "motion_estimation_cs.h" // generated by fxc at build time, see CMakeLists.txt
#include "motion_smooth_cs.h"
#include "motion_estimation_coarse_cs.h"
#include "motion_estimation_coarsest_cs.h"

namespace FrameBoost::MotionEstimation {

namespace {
// MUST stay in sync with kBlockSize in motion_estimation.hlsl and with
// Estimator::BlockSizePixels() - the dispatch grid, the shader's block
// origin maths and the interpolation shader's block lookup all depend on
// these agreeing.
constexpr UINT kBlockSize = 8;

// Pyramid: the coarse stage searches mip 2 (quarter resolution) with 16-texel
// blocks, so one coarse block covers 64 full-resolution pixels = 4x4 fine
// blocks. MUST stay in sync with motion_estimation_coarse.hlsl.
constexpr UINT kMipLevels = 5; // full, 1/2, 1/4, 1/8, 1/16 - the pyramid needs mip 4
constexpr UINT kCoarseBlockRatio = 8; // 64px coarse block / 8px fine block
constexpr UINT kCoarsestBlockRatio = 4; // coarsest blocks per coarse block, each axis

void SafeRelease(IUnknown* obj) {
    if (obj) obj->Release();
}
} // namespace

bool Estimator::EnsureResources(ID3D11Device* device, const D3D11_TEXTURE2D_DESC& frameDesc) {
    if (m_initialized && frameDesc.Width == m_width && frameDesc.Height == m_height)
        return true;

    // Resolution changed (or first run) - (re)create every GPU resource.
    SafeRelease(m_prevFrameTex); m_prevFrameTex = nullptr;
    SafeRelease(m_currFrameTex); m_currFrameTex = nullptr;
    SafeRelease(m_prevFrameSRV); m_prevFrameSRV = nullptr;
    SafeRelease(m_currFrameSRV); m_currFrameSRV = nullptr;
    SafeRelease(m_motionVectorRawTex); m_motionVectorRawTex = nullptr;
    SafeRelease(m_motionVectorRawUAV); m_motionVectorRawUAV = nullptr;
    SafeRelease(m_motionVectorRawSRV); m_motionVectorRawSRV = nullptr;
    SafeRelease(m_motionVectorSmoothTex); m_motionVectorSmoothTex = nullptr;
    SafeRelease(m_motionVectorSmoothUAV); m_motionVectorSmoothUAV = nullptr;
    SafeRelease(m_motionVectorSmoothSRV); m_motionVectorSmoothSRV = nullptr;
    SafeRelease(m_motionVectorHistoryTex); m_motionVectorHistoryTex = nullptr;
    SafeRelease(m_motionVectorHistorySRV); m_motionVectorHistorySRV = nullptr;
    m_haveMotionHistory = false;
    SafeRelease(m_coarsestMotionTex); m_coarsestMotionTex = nullptr;
    SafeRelease(m_coarsestMotionUAV); m_coarsestMotionUAV = nullptr;
    SafeRelease(m_coarsestMotionSRV); m_coarsestMotionSRV = nullptr;
    SafeRelease(m_coarseMotionTex); m_coarseMotionTex = nullptr;
    SafeRelease(m_coarseMotionUAV); m_coarseMotionUAV = nullptr;
    SafeRelease(m_coarseMotionSRV); m_coarseMotionSRV = nullptr;
    SafeRelease(m_frameDimsCB); m_frameDimsCB = nullptr;
    SafeRelease(m_blockGridDimsCB); m_blockGridDimsCB = nullptr;
    m_havePrevFrame = false;

    m_width = frameDesc.Width;
    m_height = frameDesc.Height;
    m_blockCountX = (m_width + kBlockSize - 1) / kBlockSize;
    m_blockCountY = (m_height + kBlockSize - 1) / kBlockSize;
    m_coarseCountX = (m_blockCountX + kCoarseBlockRatio - 1) / kCoarseBlockRatio;
    m_coarseCountY = (m_blockCountY + kCoarseBlockRatio - 1) / kCoarseBlockRatio;
    m_coarsestCountX = (m_coarseCountX + kCoarsestBlockRatio - 1) / kCoarsestBlockRatio;
    m_coarsestCountY = (m_coarseCountY + kCoarsestBlockRatio - 1) / kCoarsestBlockRatio;

    D3D11_TEXTURE2D_DESC frameTexDesc = frameDesc;
    frameTexDesc.Usage = D3D11_USAGE_DEFAULT;
    frameTexDesc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
    frameTexDesc.CPUAccessFlags = 0;
    frameTexDesc.MiscFlags = 0;
    frameTexDesc.SampleDesc.Count = 1;
    frameTexDesc.SampleDesc.Quality = 0;
    // Three mip levels so the pyramid's coarse stage can search level 2
    // (quarter resolution). RENDER_TARGET and GENERATE_MIPS are both required
    // for GenerateMips to be allowed to fill the chain.
    frameTexDesc.MipLevels = kMipLevels;
    frameTexDesc.BindFlags = D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_RENDER_TARGET;
    frameTexDesc.MiscFlags = D3D11_RESOURCE_MISC_GENERATE_MIPS;
    frameTexDesc.ArraySize = 1;

    if (FAILED(device->CreateTexture2D(&frameTexDesc, nullptr, &m_prevFrameTex)) ||
        FAILED(device->CreateTexture2D(&frameTexDesc, nullptr, &m_currFrameTex))) {
        Logger::Log("[FrameBoost] Motion estimation: failed to create frame textures.");
        return false;
    }

    device->CreateShaderResourceView(m_prevFrameTex, nullptr, &m_prevFrameSRV);
    device->CreateShaderResourceView(m_currFrameTex, nullptr, &m_currFrameSRV);

    D3D11_TEXTURE2D_DESC mvDesc{};
    mvDesc.Width = m_blockCountX;
    mvDesc.Height = m_blockCountY;
    mvDesc.MipLevels = 1;
    mvDesc.ArraySize = 1;
    mvDesc.Format = DXGI_FORMAT_R32G32B32A32_FLOAT;
    mvDesc.SampleDesc.Count = 1;
    mvDesc.Usage = D3D11_USAGE_DEFAULT;
    mvDesc.BindFlags = D3D11_BIND_UNORDERED_ACCESS | D3D11_BIND_SHADER_RESOURCE;

    if (FAILED(device->CreateTexture2D(&mvDesc, nullptr, &m_motionVectorRawTex)) ||
        FAILED(device->CreateTexture2D(&mvDesc, nullptr, &m_motionVectorSmoothTex))) {
        Logger::Log("[FrameBoost] Motion estimation: failed to create motion vector textures.");
        return false;
    }
    device->CreateUnorderedAccessView(m_motionVectorRawTex, nullptr, &m_motionVectorRawUAV);
    device->CreateShaderResourceView(m_motionVectorRawTex, nullptr, &m_motionVectorRawSRV);
    device->CreateUnorderedAccessView(m_motionVectorSmoothTex, nullptr, &m_motionVectorSmoothUAV);
    device->CreateShaderResourceView(m_motionVectorSmoothTex, nullptr, &m_motionVectorSmoothSRV);

    if (FAILED(device->CreateTexture2D(&mvDesc, nullptr, &m_motionVectorHistoryTex))) {
        Logger::Log("[FrameBoost] Motion estimation: failed to create the motion history texture.");
        return false;
    }
    device->CreateShaderResourceView(m_motionVectorHistoryTex, nullptr, &m_motionVectorHistorySRV);

    D3D11_TEXTURE2D_DESC coarseDesc = mvDesc;
    coarseDesc.Width = m_coarseCountX;
    coarseDesc.Height = m_coarseCountY;
    if (FAILED(device->CreateTexture2D(&coarseDesc, nullptr, &m_coarseMotionTex))) {
        Logger::Log("[FrameBoost] Motion estimation: failed to create the coarse motion texture.");
        return false;
    }
    device->CreateUnorderedAccessView(m_coarseMotionTex, nullptr, &m_coarseMotionUAV);
    device->CreateShaderResourceView(m_coarseMotionTex, nullptr, &m_coarseMotionSRV);

    D3D11_TEXTURE2D_DESC coarsestDesc = mvDesc;
    coarsestDesc.Width = m_coarsestCountX;
    coarsestDesc.Height = m_coarsestCountY;
    if (FAILED(device->CreateTexture2D(&coarsestDesc, nullptr, &m_coarsestMotionTex))) {
        Logger::Log("[FrameBoost] Motion estimation: failed to create the coarsest motion texture.");
        return false;
    }
    device->CreateUnorderedAccessView(m_coarsestMotionTex, nullptr, &m_coarsestMotionUAV);
    device->CreateShaderResourceView(m_coarsestMotionTex, nullptr, &m_coarsestMotionSRV);

    if (!m_computeShader) {
        if (FAILED(device->CreateComputeShader(g_MotionEstimationCS, sizeof(g_MotionEstimationCS), nullptr, &m_computeShader))) {
            Logger::Log("[FrameBoost] Motion estimation: failed to create block-matching compute shader.");
            return false;
        }
    }
    if (!m_coarseShader) {
        if (FAILED(device->CreateComputeShader(g_MotionEstimationCoarseCS, sizeof(g_MotionEstimationCoarseCS), nullptr, &m_coarseShader))) {
            Logger::Log("[FrameBoost] Motion estimation: failed to create the coarse pyramid compute shader.");
            return false;
        }
    }
    if (!m_coarsestShader) {
        if (FAILED(device->CreateComputeShader(g_MotionEstimationCoarsestCS, sizeof(g_MotionEstimationCoarsestCS), nullptr, &m_coarsestShader))) {
            Logger::Log("[FrameBoost] Motion estimation: failed to create the coarsest pyramid compute shader.");
            return false;
        }
    }
    if (!m_smoothShader) {
        if (FAILED(device->CreateComputeShader(g_MotionSmoothCS, sizeof(g_MotionSmoothCS), nullptr, &m_smoothShader))) {
            Logger::Log("[FrameBoost] Motion estimation: failed to create smoothing compute shader.");
            return false;
        }
    }

    // Carries every pyramid level's grid size: each level clamps its lookup
    // into the level above.
    struct FrameDimsCB {
        UINT width, height;
        UINT coarseW, coarseH;
        UINT coarsestW, coarsestH;
        UINT pad0, pad1;
    };
    FrameDimsCB frameDims{ m_width, m_height,
        m_coarseCountX, m_coarseCountY,
        m_coarsestCountX, m_coarsestCountY, 0, 0 };
    D3D11_BUFFER_DESC cbDesc{};
    cbDesc.ByteWidth = sizeof(FrameDimsCB);
    cbDesc.Usage = D3D11_USAGE_DEFAULT;
    cbDesc.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    D3D11_SUBRESOURCE_DATA cbInit{ &frameDims, 0, 0 };
    device->CreateBuffer(&cbDesc, &cbInit, &m_frameDimsCB);

    struct BlockGridDimsCB { UINT blockCountX, blockCountY, havePrevious, pad1; };
    BlockGridDimsCB gridDims{ m_blockCountX, m_blockCountY, 0, 0 }; // no history yet
    D3D11_SUBRESOURCE_DATA gridCbInit{ &gridDims, 0, 0 };
    device->CreateBuffer(&cbDesc, &gridCbInit, &m_blockGridDimsCB);

    if (!m_queries[0].disjoint) {
        for (auto& q : m_queries) {
            D3D11_QUERY_DESC disjointDesc{ D3D11_QUERY_TIMESTAMP_DISJOINT, 0 };
            D3D11_QUERY_DESC timestampDesc{ D3D11_QUERY_TIMESTAMP, 0 };
            device->CreateQuery(&disjointDesc, &q.disjoint);
            device->CreateQuery(&timestampDesc, &q.start);
            device->CreateQuery(&timestampDesc, &q.end);
        }
    }

    m_initialized = true;
    Logger::Log("[FrameBoost] Motion estimation resources created: "
        + std::to_string(m_width) + "x" + std::to_string(m_height)
        + " -> " + std::to_string(m_blockCountX) + "x" + std::to_string(m_blockCountY) + " blocks.");
    return true;
}

void Estimator::ResolvePendingGpuTiming(ID3D11DeviceContext* context) {
    // Read the OLDEST still-pending query set - by now (kQueryRingSize
    // frames later) the GPU has essentially always finished, so GetData
    // does not stall.
    int readIndex = (m_queryWriteIndex + 1) % kQueryRingSize;
    QuerySet& q = m_queries[readIndex];
    if (!q.pending) return;

    D3D11_QUERY_DATA_TIMESTAMP_DISJOINT disjointData{};
    if (context->GetData(q.disjoint, &disjointData, sizeof(disjointData), 0) != S_OK) return;

    UINT64 start = 0, end = 0;
    if (context->GetData(q.start, &start, sizeof(start), 0) != S_OK) return;
    if (context->GetData(q.end, &end, sizeof(end), 0) != S_OK) return;

    q.pending = false;
    if (disjointData.Disjoint || disjointData.Frequency == 0) return;

    // Covers BOTH GPU passes (block-matching + smoothing) since the
    // timestamps now bracket both dispatches - the number logged is the
    // real total motion-estimation cost, not just one half of it.
    m_lastGpuTimeMs = static_cast<double>(end - start) / disjointData.Frequency * 1000.0;
}

bool Estimator::ProcessFrame(ID3D11Device* device, ID3D11DeviceContext* context, ID3D11Texture2D* backBuffer) {
    D3D11_TEXTURE2D_DESC desc{};
    backBuffer->GetDesc(&desc);

    if (!EnsureResources(device, desc))
        return false;

    // Into mip 0, then let the GPU build the chain: the pyramid's coarse stage
    // searches mip 2. CopyResource cannot be used any more now that the
    // destination has mips and the source does not.
    context->CopySubresourceRegion(m_currFrameTex, 0, 0, 0, 0, backBuffer, 0, nullptr);
    context->GenerateMips(m_currFrameSRV);

    bool computedThisFrame = false;

    if (m_havePrevFrame) {
        QuerySet& q = m_queries[m_queryWriteIndex];
        context->Begin(q.disjoint);
        context->End(q.start);

        ID3D11ShaderResourceView* nullSrvs[3] = { nullptr, nullptr, nullptr };
        ID3D11UnorderedAccessView* nullUav = nullptr;

        // Pass 1a: COARSEST search on mip 4 (one sixteenth resolution). One
        // texel spans 16 full-resolution pixels, so radius 12 reaches 192 px.
        // Almost free - 256x fewer blocks than at full resolution.
        ID3D11ShaderResourceView* frameSrvs[2] = { m_prevFrameSRV, m_currFrameSRV };
        context->CSSetShaderResources(0, 2, frameSrvs);
        context->CSSetUnorderedAccessViews(0, 1, &m_coarsestMotionUAV, nullptr);
        context->CSSetConstantBuffers(0, 1, &m_frameDimsCB);
        context->CSSetShader(m_coarsestShader, nullptr, 0);
        context->Dispatch(m_coarsestCountX, m_coarsestCountY, 1);

        context->CSSetShaderResources(0, 2, nullSrvs);
        context->CSSetUnorderedAccessViews(0, 1, &nullUav, nullptr);

        // Pass 1b: COARSE search on mip 2 (quarter resolution), refining the
        // coarsest result by +-24 px rather than searching from zero.
        ID3D11ShaderResourceView* coarseSrvs[3] = { m_prevFrameSRV, m_currFrameSRV, m_coarsestMotionSRV };
        context->CSSetShaderResources(0, 3, coarseSrvs);
        context->CSSetUnorderedAccessViews(0, 1, &m_coarseMotionUAV, nullptr);
        context->CSSetShader(m_coarseShader, nullptr, 0);
        context->Dispatch(m_coarseCountX, m_coarseCountY, 1);

        context->CSSetShaderResources(0, 3, nullSrvs);
        context->CSSetUnorderedAccessViews(0, 1, &nullUav, nullptr);

        // Pass 1b: FINE search at full resolution, seeded by the coarse
        // result and only refining +-6 px around it. Total reach 54 px, at
        // 169 candidates per block instead of the 625 the old single-stage
        // search needed for a reach of 12.
        ID3D11ShaderResourceView* fineSrvs[3] = { m_prevFrameSRV, m_currFrameSRV, m_coarseMotionSRV };
        context->CSSetShaderResources(0, 3, fineSrvs);
        context->CSSetUnorderedAccessViews(0, 1, &m_motionVectorRawUAV, nullptr);
        context->CSSetShader(m_computeShader, nullptr, 0);
        context->Dispatch(m_blockCountX, m_blockCountY, 1);

        context->CSSetShaderResources(0, 3, nullSrvs);
        context->CSSetUnorderedAccessViews(0, 1, &nullUav, nullptr);

        // Pass 2: 5x5 spatial smoothing plus temporal blending against the
        // previous frame's field - the fix for speckle noise and for the
        // "wiggling" reported in a game, where the image warped slightly
        // differently from frame to frame.
        {
            struct BlockGridDimsCB { UINT blockCountX, blockCountY, havePrevious, pad1; };
            BlockGridDimsCB gridDims{ m_blockCountX, m_blockCountY, m_haveMotionHistory ? 1u : 0u, 0 };
            context->UpdateSubresource(m_blockGridDimsCB, 0, nullptr, &gridDims, 0, 0);
        }

        ID3D11ShaderResourceView* smoothSrvs[2] = { m_motionVectorRawSRV, m_motionVectorHistorySRV };
        context->CSSetShaderResources(0, 2, smoothSrvs);
        context->CSSetUnorderedAccessViews(0, 1, &m_motionVectorSmoothUAV, nullptr);
        context->CSSetConstantBuffers(0, 1, &m_blockGridDimsCB);
        context->CSSetShader(m_smoothShader, nullptr, 0);
        UINT groupsX = (m_blockCountX + 7) / 8;
        UINT groupsY = (m_blockCountY + 7) / 8;
        context->Dispatch(groupsX, groupsY, 1);

        ID3D11ShaderResourceView* nullSrv2[2] = { nullptr, nullptr };
        context->CSSetShaderResources(0, 2, nullSrv2);
        context->CSSetUnorderedAccessViews(0, 1, &nullUav, nullptr);

        // Keep this field as history for the next frame's temporal blend.
        context->CopyResource(m_motionVectorHistoryTex, m_motionVectorSmoothTex);
        m_haveMotionHistory = true;

        context->End(q.end);
        context->End(q.disjoint);
        q.pending = true;
        m_queryWriteIndex = (m_queryWriteIndex + 1) % kQueryRingSize;

        ResolvePendingGpuTiming(context);
        computedThisFrame = true;
    }

    // Current becomes previous for the next frame - stays entirely GPU-side.
    context->CopyResource(m_prevFrameTex, m_currFrameTex);
    m_havePrevFrame = true;

    return computedThisFrame;
}

Estimator::~Estimator() {
    SafeRelease(m_prevFrameTex);
    SafeRelease(m_currFrameTex);
    SafeRelease(m_prevFrameSRV);
    SafeRelease(m_currFrameSRV);
    SafeRelease(m_motionVectorRawTex);
    SafeRelease(m_motionVectorRawUAV);
    SafeRelease(m_motionVectorRawSRV);
    SafeRelease(m_motionVectorSmoothTex);
    SafeRelease(m_motionVectorSmoothUAV);
    SafeRelease(m_motionVectorSmoothSRV);
    SafeRelease(m_computeShader);
    SafeRelease(m_smoothShader);
    SafeRelease(m_coarseShader);
    SafeRelease(m_coarsestShader);
    SafeRelease(m_coarsestMotionTex);
    SafeRelease(m_motionVectorHistoryTex);
    SafeRelease(m_motionVectorHistorySRV);
    SafeRelease(m_coarsestMotionUAV);
    SafeRelease(m_coarsestMotionSRV);
    SafeRelease(m_coarseMotionTex);
    SafeRelease(m_coarseMotionUAV);
    SafeRelease(m_coarseMotionSRV);
    SafeRelease(m_frameDimsCB);
    SafeRelease(m_blockGridDimsCB);
    for (auto& q : m_queries) {
        SafeRelease(q.disjoint);
        SafeRelease(q.start);
        SafeRelease(q.end);
    }
}

} // namespace FrameBoost::MotionEstimation
