#include "motion_blur.h"
#include "logger.h"

#include "motion_blur_cs.h" // generated by fxc at build time

#include <cstring>

namespace {

struct BlurParams {
    UINT  width, height, blockSize, samples;
    float shutter, maxLength, staticThreshold;
    UINT  debug;
    float minLength;
    float motionScale;
    UINT  pixelSelect;
    UINT  usePyramid;
};
static_assert(sizeof(BlurParams) % 16 == 0, "constant buffers are 16-byte multiples");

template <typename T> void SafeRelease(T*& p) { if (p) { p->Release(); p = nullptr; } }

} // namespace

MotionBlur::~MotionBlur()
{
    SafeRelease(m_shader);
    SafeRelease(m_sampler);
    SafeRelease(m_params);
    SafeRelease(m_outUAV);
    SafeRelease(m_outTex);
    for (int i = 0; i < kViewCache; ++i) SafeRelease(m_viewSRV[i]);
    for (int i = 0; i < kQueries; ++i) {
        SafeRelease(m_disjoint[i]); SafeRelease(m_start[i]); SafeRelease(m_end[i]);
    }
}

bool MotionBlur::EnsureResources(ID3D11Device* device, UINT width, UINT height)
{
    if (!m_shader) {
        if (FAILED(device->CreateComputeShader(g_MotionBlurCS, sizeof(g_MotionBlurCS), nullptr, &m_shader)))
            return false;

        D3D11_SAMPLER_DESC sd{};
        sd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
        sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        sd.MaxLOD = D3D11_FLOAT32_MAX;
        if (FAILED(device->CreateSamplerState(&sd, &m_sampler))) return false;

        D3D11_BUFFER_DESC bd{};
        bd.ByteWidth = sizeof(BlurParams);
        bd.Usage = D3D11_USAGE_DYNAMIC;
        bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
        bd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
        if (FAILED(device->CreateBuffer(&bd, nullptr, &m_params))) return false;

        D3D11_QUERY_DESC dq{ D3D11_QUERY_TIMESTAMP_DISJOINT, 0 };
        D3D11_QUERY_DESC tq{ D3D11_QUERY_TIMESTAMP, 0 };
        for (int i = 0; i < kQueries; ++i) {
            device->CreateQuery(&dq, &m_disjoint[i]);
            device->CreateQuery(&tq, &m_start[i]);
            device->CreateQuery(&tq, &m_end[i]);
        }
    }

    if (m_outTex && m_width == width && m_height == height) return true;
    SafeRelease(m_outUAV);
    SafeRelease(m_outTex);

    // The same format the presenter already takes from the interpolator, so it
    // copies this without any conversion.
    D3D11_TEXTURE2D_DESC td{};
    td.Width = width;
    td.Height = height;
    td.MipLevels = 1;
    td.ArraySize = 1;
    td.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
    td.SampleDesc.Count = 1;
    td.Usage = D3D11_USAGE_DEFAULT;
    td.BindFlags = D3D11_BIND_UNORDERED_ACCESS | D3D11_BIND_SHADER_RESOURCE;
    if (FAILED(device->CreateTexture2D(&td, nullptr, &m_outTex))) return false;
    if (FAILED(device->CreateUnorderedAccessView(m_outTex, nullptr, &m_outUAV))) return false;
    m_width = width;
    m_height = height;
    return true;
}

ID3D11ShaderResourceView* MotionBlur::SourceView(ID3D11Device* device, ID3D11Texture2D* source)
{
    for (int i = 0; i < kViewCache; ++i)
        if (m_viewTex[i] == source && m_viewSRV[i]) return m_viewSRV[i];

    D3D11_TEXTURE2D_DESC desc{};
    source->GetDesc(&desc);
    if (!(desc.BindFlags & D3D11_BIND_SHADER_RESOURCE)) return nullptr;

    // Only the top level: a source with mips (the estimator's copy builds a
    // pyramid for the motion search) is read at full resolution here.
    D3D11_SHADER_RESOURCE_VIEW_DESC vd{};
    vd.Format = desc.Format;
    vd.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
    vd.Texture2D.MostDetailedMip = 0;
    vd.Texture2D.MipLevels = 1;

    const int slot = m_viewNext;
    m_viewNext = (m_viewNext + 1) % kViewCache;
    SafeRelease(m_viewSRV[slot]);
    m_viewTex[slot] = nullptr;
    if (FAILED(device->CreateShaderResourceView(source, &vd, &m_viewSRV[slot]))) return nullptr;
    m_viewTex[slot] = source;
    return m_viewSRV[slot];
}

ID3D11Texture2D* MotionBlur::Apply(ID3D11Device* device, ID3D11DeviceContext* context,
                                   ID3D11Texture2D* source,
                                   ID3D11ShaderResourceView* prevSRV, ID3D11ShaderResourceView* currSRV,
                                   ID3D11ShaderResourceView* motionSRV, UINT width, UINT height, UINT blockSize)
{
    if (m_failed || !source || !prevSRV || !currSRV || !motionSRV) return nullptr;
    if (!EnsureResources(device, width, height)) {
        m_failed = true;
        fbv2::Logger::Log("[FrameBoostV2] Motion blur could not create its resources - running without it.");
        return nullptr;
    }
    ID3D11ShaderResourceView* sourceSRV = SourceView(device, source);
    if (!sourceSRV) return nullptr;

    // Read back the oldest timing that has finished; never wait for one.
    const int q = m_query;
    m_query = (m_query + 1) % kQueries;
    if (m_pending[q]) {
        D3D11_QUERY_DATA_TIMESTAMP_DISJOINT dj{};
        UINT64 t0 = 0, t1 = 0;
        if (context->GetData(m_disjoint[q], &dj, sizeof(dj), D3D11_ASYNC_GETDATA_DONOTFLUSH) == S_OK &&
            context->GetData(m_start[q], &t0, sizeof(t0), D3D11_ASYNC_GETDATA_DONOTFLUSH) == S_OK &&
            context->GetData(m_end[q], &t1, sizeof(t1), D3D11_ASYNC_GETDATA_DONOTFLUSH) == S_OK &&
            !dj.Disjoint && dj.Frequency) {
            m_lastGpuMs = double(t1 - t0) * 1000.0 / double(dj.Frequency);
        }
        m_pending[q] = false;
    }

    D3D11_MAPPED_SUBRESOURCE mapped{};
    if (FAILED(context->Map(m_params, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) return nullptr;
    // Up to 24 samples (one per ~5 px) along at most 128 pixels - 96 cut fast
    // flicks short. The cap keeps a wrong giant vector from smearing half the
    // screen. The shader no longer reads the still threshold.
    BlurParams p{ width, height, blockSize, 32u, m_shutter, 256.0f, m_stillProtection ? 0.03f : 0.0f, m_debug, m_minLength, m_motionScale, m_pixelSelect ? 1u : 0u, m_usePyramid ? 1u : 0u };
    memcpy(mapped.pData, &p, sizeof(p));
    context->Unmap(m_params, 0);

    if (m_disjoint[q]) { context->Begin(m_disjoint[q]); context->End(m_start[q]); }

    ID3D11ShaderResourceView* srvs[4] = { sourceSRV, prevSRV, currSRV, motionSRV };
    context->CSSetShader(m_shader, nullptr, 0);
    context->CSSetShaderResources(0, 4, srvs);
    context->CSSetUnorderedAccessViews(0, 1, &m_outUAV, nullptr);
    context->CSSetConstantBuffers(0, 1, &m_params);
    context->CSSetSamplers(0, 1, &m_sampler);
    context->Dispatch((width + 7) / 8, (height + 7) / 8, 1);

    // Unbind, so the next pass can use these textures as targets.
    ID3D11ShaderResourceView* nullSrvs[4] = {};
    ID3D11UnorderedAccessView* nullUav = nullptr;
    context->CSSetShaderResources(0, 4, nullSrvs);
    context->CSSetUnorderedAccessViews(0, 1, &nullUav, nullptr);

    if (m_disjoint[q]) { context->End(m_end[q]); context->End(m_disjoint[q]); m_pending[q] = true; }
    return m_outTex;
}
